spring:
  datasource:
    url: jdbc:sqlite:swsecintro.sqlite
    driver-class-name: org.sqlite.JDBC

logging:
  level:
    org.springframework.web: DEBUG

jwt:
  secret: 12345
  duration_milliseconds: 86400000